---
- name: update jenkins server
  hosts: jk
  become: yes
  remote_user: ubuntu
  
  
  
  tasks:
    
    - name: create a directory
      file:
        path: /home/newfolder
        state: directory

    - name: Create an empty file
      file:
        path: /home/newfolder/file1.txt
        state: touch