---
-  hosts: all
-  import_playbook: /home/ec2-user/ansible/Ansible-config-mgt./static-assignments/common.yml


-  hosts: uat-webservers
-  import_playbook: /home/ec2-user/ansible/Ansible-config-mgt./static-assignments/uat-webservers.yml

-  name: Include dynamic variables
   hosts: all
   tasks:

      - import_playbook: ../static-assignments/common.yml
      - include_playbook: ../dynamic-assignments/env-vars.yml
   tags:
      - always
     
-  name: Webserver assignment
   hosts: uat-webservers
      - import_playbook: ../static-assignments/uat-webservers.yml
